version: '3'
services:

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env.prod.database

  app:
    build: .
    expose:
      - 8000
    volumes:
      - static:/app/static:rw
      - dist:/app/dist:rw
    env_file:
      - .env.prod.app
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./logs/nginx:/var/log/nginx:rw
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - dist:/usr/share/nginx/html/dist/:ro
      - static:/usr/share/nginx/html/static/:ro
    depends_on:
      - app

volumes:
  static:
  postgres_data:
  dist:
